# Logs and checkpoints
LOGS_DIR: "logs"

# Dataset
DATASET_BUILDER_PATH: "src/data/parquet_description_builder.py"
CACHE_DIR: "cache"
DOWNLOAD_CFG_PATH: "tmp"
DATA_NAME: "brandbank_50000_examples_100_groups"
DATA_DIR: "/home/azureuser/cloudfiles/code/Users/Fernando.Rodriguez/ainn-eliza-rnd-data/multimodal_dataloader_v1/data/brandbank_50000_examples_100_groups/splits"
MAX_SEQ_LENGTH: 64
LABEL_NAME: "PRODUCT_GROUP"
IGNORE_LABELS:
  - "OUT OF SCOPE"

# Training
MODEL_NAME: "DISTILBERT_BASE"
BATCH_SIZE: 64
LEARNING_RATE: 5e-5
PRECISION: "16-mixed"
NUM_EPOCHS: 4
NUM_WORKERS: 1
LOG_INTERVAL: 1

# Compute related
COMPUTE_ACCELERATOR: "gpu"
COMPUTE_DEVICES: 1